### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by fps** [Treatz/phiction_phreak#1]
<pre>
$ qmake searchWidget.pro 
WARNING: Failure to find: mainwindow.ui
</pre>

I suppose you forgot to add that file..

**Comment by Treatz** [comment]
I sent you the file as an attatchment.  Unfortunately I can't update
the github yet.  But can you download this and compile it?

**Comment by fps** [comment]
the merge seems to have fixed the issue

**Comment by Treatz** [comment]
I'm trying to upload a release of the windows binary package, but it still
says I have 0 repositories.  The binary is uploaded but it is saved as a
draft? Can you help me with this too please?

**Comment by Treatz** [comment]
Aha, I got it.  I just needed to give it a version number.

**Comment by Treatz** [comment]
Also, do I need to tell people what Qt is somewhere in the page?  I want to
create a good project page as well, with some kind of theme.

**Comment by Treatz** [comment]
Okay, sorry to bother you again but I have my project page up @
http://treatz.github.io/phiction_phreak/
I need to know how I can give people the ability to download the actual
binaries through this page.  Is this possible?

**Comment by Treatz** [comment]
fps:  I just added a link to the bottom of the page at
treatz.github.io/phiction_phreak/
That should do for now.  My only other question is if you can get it to
compile on a mac for me?
Please...?

**Comment by fps** [comment]
Hi, sorry to come back to you only at this time. i can take a look if I can locate a compile/build service with OS X support for this open source project :) Sadly right now i'm a bit busy. Maybe tomorrow..

**Comment by Treatz** [comment]
That's okay.  Right now I am trying to find a way to use SQLite instead of
coding the whole database into C++.  Do you know SQLite, or could recommend
a good book on it for C++ maybe?

**Comment by fps** [comment]
SQLite has a C interface which is ugly but not too compiicated if I remember correctly.

**Comment by fps** [comment]
but let's move the discussion here: https://github.com/Treatz/phiction_phreak/issues/4
